line-length = 79

select = ["ALL"]

ignore = [
    # flake8-bandit (S)
    "S101", 	# assert: Use of assert detected

    # isort (I)
    "I001",	    # Unsorted-imports: Import block is un-sorted or un-formatted

    # flake8-annotations (ANN)
    "ANN101",	# Missing-type-self: Missing type annotation
                # for self in method
    "ANN102",   # Missing-type-cls: Missing type annotation
                # for cls in classmethod
    "ANN204",	# Missing-return-type-special-method: Missing return type
                # annotation for special method __init__
    "ANN401",   # Any-type: dynamically typed expressions (typing.Any)
                # are disallowed in {name}

    # pydocstyle (D)
    "D107",	    # Public-init: Missing docstring in __init__
    "D203",     # D203 and D211 are incompatible
    "D205",     # Blank-line-after-summary
    "D212",     # D212 and D213 are incompatible
    "D401",     # Non-imperative-mood

    # pylint refactor (R)
    "PLR0913",	# Too-many-arguments:
                # Too many arguments to function call ({c_args}/{max_args})

    # pyupgrade (UP)
    "UP035",    # Import-replacements: Import from {module} instead:

    # Ruff-specific rules (RUF)
    "RUF001",   # Ambiguous-unicode-character-string: Broken rule
    "RUF002",   # Ambiguous-unicode-character-docstring: Broken rule
    "RUF003",   # Ambiguous-unicode-character-comment: Broken rule

    # flake8-unused-arguments (ARG)
    "ARG001",   # Unused-function-argument
    "ARG002",   # Unused-method-argument

    # flake8-bugbear (B)
#    "B027",     # Empty-method-without-abstract-decorator

    # Eradicate (ERA)
    "ERA001",    # Found commented-out code
]

[pep8-naming]
ignore-names = ["k", "v", "i", "q", "fp", "x", "y", "z"]
